# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.11-slim

# Set work directory
WORKDIR /app

# Install dependencies
COPY pyproject.toml /app/
RUN apt-get update && apt-get install -y --no-install-recommends \
        build-essential \
    && pip install --no-cache-dir -U pip \
    && pip install --no-cache-dir .[cli]

# Copy application code
COPY . /app/

# Expose SSE port
EXPOSE 8001

# Default command
CMD ["python", "server.py"]
